/home/matt/naps/naps-1.02b/es1sat/core/Main.o /home/matt/naps/naps-1.02b/es1sat/core/Main.or /home/matt/naps/naps-1.02b/es1sat/core/Main.od /home/matt/naps/naps-1.02b/es1sat/core/Main.op: /home/matt/naps/naps-1.02b/es1sat/core/Main.cc \
 /home/matt/naps/naps-1.02b/es1sat/utils/System.h \
 /home/matt/naps/naps-1.02b/es1sat/utils/../mtl/IntTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/utils/ParseUtils.h \
 /home/matt/naps/naps-1.02b/es1sat/utils/Options.h \
 /home/matt/naps/naps-1.02b/es1sat/utils/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/utils/../mtl/../mtl/IntTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/utils/../mtl/../mtl/XAlloc.h \
 /home/matt/naps/naps-1.02b/es1sat/utils/../utils/ParseUtils.h \
 /home/matt/naps/naps-1.02b/es1sat/core/Dimacs.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../utils/ParseUtils.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/SolverTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/IntTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/Alg.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/Map.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/../mtl/IntTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/Alloc.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/../mtl/XAlloc.h \
 /home/matt/naps/naps-1.02b/es1sat/core/Solver.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../mtl/Heap.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../mtl/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../mtl/Alg.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../utils/Options.h
/home/matt/naps/naps-1.02b/es1sat/core/Solver.o /home/matt/naps/naps-1.02b/es1sat/core/Solver.or /home/matt/naps/naps-1.02b/es1sat/core/Solver.od /home/matt/naps/naps-1.02b/es1sat/core/Solver.op: /home/matt/naps/naps-1.02b/es1sat/core/Solver.cc \
 /home/matt/naps/naps-1.02b/es1sat/mtl/Sort.h \
 /home/matt/naps/naps-1.02b/es1sat/mtl/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/mtl/../mtl/../mtl/IntTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/mtl/../mtl/../mtl/XAlloc.h \
 /home/matt/naps/naps-1.02b/es1sat/core/Solver.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../mtl/Heap.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../mtl/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../mtl/Alg.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../utils/Options.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../utils/../mtl/IntTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../utils/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../utils/../utils/ParseUtils.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/SolverTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/IntTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/Alg.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/Map.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/../mtl/IntTypes.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/../mtl/Vec.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/Alloc.h \
 /home/matt/naps/naps-1.02b/es1sat/core/../core/../mtl/../mtl/XAlloc.h
